import ENUM from "./ENUM";

export default ENUM(class {
    WORD_EDIT_WORD
    WORD_REMOVE_WORD
    WORD_APROVE_WORD
    WORD_SET_DEFINITION
    WORD_CREATE

    ORG_OWNER
    ORG_ADMIN_MANAGE_USERS
    ORG_ADMIN_UPLOAD_WORDS
    ORG_ADMIN_REMOVE_USERS
}, true);